# Generated by Django 4.2.2 on 2024-01-02 11:56

from django.db import migrations, models
import django_editorjs.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('label', models.CharField(choices=[('Speaking', 'Speaking'), ('Project', 'Project')], max_length=200, null=True)),
                ('overview', django_editorjs.fields.EditorJsField()),
                ('image', models.ImageField(upload_to='')),
                ('image_1', models.URLField(blank=True, null=True)),
                ('image_2', models.URLField(blank=True, null=True)),
                ('image_3', models.URLField(blank=True, null=True)),
                ('image_4', models.URLField(blank=True, null=True)),
                ('image_5', models.URLField(blank=True, null=True)),
                ('image_6', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
