# Generated by Django 4.2 on 2024-03-18 09:46

from django.db import migrations, models
import django_tiptap.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('label', models.CharField(choices=[('Speaking', 'Speaking'), ('Project', 'Project')], max_length=200, null=True)),
                ('content', django_tiptap.fields.TipTapTextField()),
                ('image', models.ImageField(upload_to='')),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
