# Generated by Django 4.2.2 on 2024-01-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image_6',
        ),
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
