# Generated by Django 4.2 on 2024-03-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
    ]
