# Generated by Django 4.2 on 2024-02-05 05:11

import datetime
from django.db import migrations
import django_tiptap.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_work_github_link_remove_work_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='overview',
        ),
        migrations.AddField(
            model_name='work',
            name='content',
            field=django_tiptap.fields.TipTapTextField(default=datetime.datetime(2024, 2, 5, 5, 11, 36, 748626, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
