# Generated by Django 4.2 on 2024-03-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_work_overview_work_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
